[project]
name = "pyratapprox"
version = "0.1.0"
description = "Python interface for rational function approximation via Julia"
authors = [{name = "Toby Driscoll", email = "driscoll@udel.edu"}]
readme = "README.md"
requires-python = ">= 3.11"
license = {text = "MIT"}
keywords = ["rational approximation", "interpolation", "AAA", "numerical analysis"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = ["juliacall>=0.9.31,<0.10", "cxregions>=0.1.4,<0.2", "hatch>=1.16.3,<2"]

[project.urls]
Homepage = "https://complexvariables.github.io/pyratapprox"
Documentation = "https://complexvariables.github.io/pyratapprox"
Repository = "https://github.com/complexvariables/pyratapprox"
Issues = "https://github.com/complexvariables/pyratapprox/issues"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tool.pixi.pypi-dependencies]
pyratapprox = { path = ".", editable = true }

[tool.pixi.tasks]

[tool.pixi.dependencies]
numpy = ">=2.4.0,<3"
ipykernel = ">=7.1.0,<8"
python = "3.13.*"
twine = ">=6.2.0,<7"

[tool.pixi.environments]
dev = ["doc", "test"]

[tool.pixi.feature.test.dependencies]
pytest = ">=9.0.2,<10"

[tool.pixi.feature.doc.dependencies]
jupyter = "*"
scipy = ">=1.17.0,<2"

[tool.pixi.feature.doc.pypi-dependencies]
quartodoc = "*"

[tool.pixi.feature.doc.tasks]
build-docs = "cd docs && quartodoc build && quarto render"

[dependency-groups]
doc = ["matplotlib>=3.10.8,<4"]
