project:
  type: website
  render:
    - "*.qmd"

website:
  title: "pyratapprox"
  favicon: i-con.ico
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: reference/index.qmd
        text: Reference
    right:
      - icon: github
        href: https://github.com/complexvariables/pyratapprox
  sidebar:
    search: true
    contents:
      - href: index.qmd
        text: Home
      - href: structure.qmd
        text: Package structure
      - href: comparison.qmd
        text: Comparison to SciPy
  repo-url: https://github.com/complexvariables/pyratapprox
  repo-actions: [source, issue] 

jupyter: python3

format:
  html:
    theme:
      - spacelab
    css: styles.css
    toc: true

quartodoc:
  style: pkgdown
  dir: reference
  parser: google
  package: pyratapprox
  render_interlinks: true
  sidebar: reference/_sidebar.yml
  css: reference/_styles-quartodoc.css

  sections:
    - title: Approximation
      desc: The main entry point of the package.
      contents:
        - approximate
    - title: Rational functions
      desc: How rational functions are represented in `pyratapprox`.
      contents:
        - JuliaRatfun
        - JuliaRatinterp
        - Bary
        - Thiele
    - title: Approximations
      desc: Rational approximations over domains.
      contents:
        - JuliaApprox
        - ContinuumApprox
        - DiscreteApprox
        - ConvergenceStatus

filters:
  - interlinks

# interlinks:
#   sources:
#     pyratapprox:
#       url: https://complexvariables.github.io/pyratapprox
    # cxregions:
      # url: https://complexvariables.github.io/cxregions