# ContinuumApprox { #pyratapprox.ContinuumApprox }

```python
ContinuumApprox(julia_obj)
```

Rational approximation on a continuum domain.

Represents a rational function approximation computed on a continuous domain
such as a curve, path, or region in the complex plane. The approximation is
constructed adaptively using methods like AAA or TCF.

## Attributes {.doc-section .doc-section-attributes}

| Name     | Type   | Description                                                                       |
|----------|--------|-----------------------------------------------------------------------------------|
| julia    |        | The underlying Julia ContinuumApproximation object.                               |
| original |        | The original function being approximated.                                         |
| domain   |        | The continuum domain (curve, path, or region).                                    |
| fun      |        | The rational function approximation (Thiele, Bary, etc.).                         |
| allowed  |        | Allowed pole locations.                                                           |
| path     |        | Integration path used in approximation.                                           |
| history  |        | History of the approximation process.                                             |
| status   |        | ConvergenceStatus saying why the iteration stopped, or None if none was recorded. |

## Methods

| Name | Description |
| --- | --- |
| [getfunction](#pyratapprox.ContinuumApprox.getfunction) | Get the underlying rational function. |
| [isapprox](#pyratapprox.ContinuumApprox.isapprox) | Check if this approximation is close to another function. |
| [nodes](#pyratapprox.ContinuumApprox.nodes) | Get the interpolation nodes of the approximation. |
| [testpoints](#pyratapprox.ContinuumApprox.testpoints) | Get the test points used to validate the approximation. |
| [values](#pyratapprox.ContinuumApprox.values) | Get the function values at the interpolation nodes. |

### getfunction { #pyratapprox.ContinuumApprox.getfunction }

```python
ContinuumApprox.getfunction()
```

Get the underlying rational function.

#### Returns {.doc-section .doc-section-returns}

| Name   | Type   | Description                                                        |
|--------|--------|--------------------------------------------------------------------|
|        |        | Thiele, Bary, or JuliaRatfun: The rational function approximation. |

### isapprox { #pyratapprox.ContinuumApprox.isapprox }

```python
ContinuumApprox.isapprox(other)
```

Check if this approximation is close to another function.

#### Parameters {.doc-section .doc-section-parameters}

| Name   | Type   | Description                               | Default    |
|--------|--------|-------------------------------------------|------------|
| other  |        | Another JuliaApprox or callable function. | _required_ |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type   | Description                                      |
|--------|--------|--------------------------------------------------|
| bool   |        | True if approximations are close on test points. |

### nodes { #pyratapprox.ContinuumApprox.nodes }

```python
ContinuumApprox.nodes()
```

Get the interpolation nodes of the approximation.

#### Returns {.doc-section .doc-section-returns}

| Name   | Type   | Description                          |
|--------|--------|--------------------------------------|
|        |        | np.ndarray: Array of node locations. |

### testpoints { #pyratapprox.ContinuumApprox.testpoints }

```python
ContinuumApprox.testpoints()
```

Get the test points used to validate the approximation.

#### Returns {.doc-section .doc-section-returns}

| Name   | Type   | Description                                |
|--------|--------|--------------------------------------------|
|        |        | np.ndarray: Array of test point locations. |

### values { #pyratapprox.ContinuumApprox.values }

```python
ContinuumApprox.values()
```

Get the function values at the interpolation nodes.

#### Returns {.doc-section .doc-section-returns}

| Name   | Type   | Description                           |
|--------|--------|---------------------------------------|
|        |        | np.ndarray: Array of function values. |