# JuliaRatinterp { #pyratapprox.JuliaRatinterp }

```python
JuliaRatinterp(julia_obj)
```

Python wrapper for Julia rational interpolants.

Extends JuliaRatfun to include interpolation-specific functionality such as
accessing interpolation nodes and values. This is the base class for specific
interpolation methods like Thiele and Barycentric.

## Attributes {.doc-section .doc-section-attributes}

| Name   | Type   | Description                                       |
|--------|--------|---------------------------------------------------|
| julia  |        | The underlying Julia rational interpolant object. |

## Methods

| Name | Description |
| --- | --- |
| [length](#pyratapprox.JuliaRatinterp.length) | Get the number of interpolation points. |
| [nodes](#pyratapprox.JuliaRatinterp.nodes) | Get the interpolation nodes. |
| [values](#pyratapprox.JuliaRatinterp.values) | Get the interpolation values at the nodes. |

### length { #pyratapprox.JuliaRatinterp.length }

```python
JuliaRatinterp.length()
```

Get the number of interpolation points.

#### Returns {.doc-section .doc-section-returns}

| Name   | Type   | Description                         |
|--------|--------|-------------------------------------|
| int    |        | Number of nodes in the interpolant. |

### nodes { #pyratapprox.JuliaRatinterp.nodes }

```python
JuliaRatinterp.nodes()
```

Get the interpolation nodes.

#### Returns {.doc-section .doc-section-returns}

| Name   | Type   | Description                                        |
|--------|--------|----------------------------------------------------|
|        |        | np.ndarray: Array of interpolation node locations. |

### values { #pyratapprox.JuliaRatinterp.values }

```python
JuliaRatinterp.values()
```

Get the interpolation values at the nodes.

#### Returns {.doc-section .doc-section-returns}

| Name   | Type   | Description                                                  |
|--------|--------|--------------------------------------------------------------|
|        |        | np.ndarray: Array of function values at interpolation nodes. |